import telebot
from telebot import types
import sqlite3


bot = telebot.TeleBot('6901942912:AAGWPmGt_PFGp_wKnBivxvXur_tiBbgunMk')

def translate(word_input, language):
    word = word_input.lower()
    previous_line = ''
    with open('ENRUS.TXT') as file:
        for line in file:
            line = line.rstrip('\n')
            string = line.split(', ')
            if len(string) > 1:
                if word in string:
                    if language == 'русский':
                        return previous_line
                    else:
                        return file.readline()
            else:
                if line == word:
                    if language == 'русский':
                        return previous_line
                    else:
                        return file.readline()
            previous_line = line
    return 'Слово не найдено'

menu = None

@bot.message_handler(commands=['start'])
def start(message):
    id_user = message.from_user.id
    conn = sqlite3.connect('users_data.sql')
    cur = conn.cursor()
    cur.execute("""CREATE TABLE IF NOT EXISTS Users(
                id int primary key,
                learnt_grammar int,
                learnt_texts int)""")
    conn.commit()
    cur.close()
    conn.close()
    conn = sqlite3.connect('users_data.sql')
    cur = conn.cursor()
    cur.execute("INSERT OR IGNORE INTO Users VALUES ('%s', '%s', '%s')" % (id_user, 0, 0))
    conn.commit()
    cur.close()
    conn.close()
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
    btn_1 = types.KeyboardButton('Переводчик')
    markup.row(btn_1)
    btn_2 = types.KeyboardButton('Грамматика')
    btn_3 = types.KeyboardButton('Чтение')
    markup.row(btn_2, btn_3)
    bot.send_message(message.chat.id, 'Выбери раздел, который хочешь изучить', reply_markup=markup)
    bot.register_next_step_handler(message, on_click)

def on_click(message):
    if message.text == 'Меню' or message.text == 'К сожалению, ты прошел все задания. Возвращайся позже':
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('Перевод')
        markup.row(btn_1)
        btn_2 = types.KeyboardButton('Грамматика')
        btn_3 = types.KeyboardButton('Чтение')
        markup.row(btn_2, btn_3)
        bot.send_message(message.chat.id, 'Выбери раздел, который хочешь изучить', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)


    if message.text == 'Чтение':
        connection = sqlite3.connect('users_data.sql')
        cursor = connection.cursor()
        cursor.execute('SELECT learnt_texts FROM Users WHERE id == ?', (message.from_user.id,))
        results = cursor.fetchall()
        cursor.close()
        connection.close()
        if results[0][0]==0:
            f = open('text_1.txt','r')
            for i in range(14):
                bot.send_message(message.chat.id, str(f.readline()).strip())
            f.close()
            markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
            next = types.KeyboardButton('Начать вопросы к тексту 1')
            markup.row(next)
            exit_from_vocabulary = types.KeyboardButton('Меню')
            markup.row(exit_from_vocabulary)
            bot.send_message(message.chat.id, 'Готов ли ты к вопросу?', reply_markup=markup)
            bot.register_next_step_handler(message, on_click)
        if results[0][0]==1:
            f = open('text_2.txt','r')
            for i in range(7):
                bot.send_message(message.chat.id, str(f.readline()).strip())
            f.close()
            markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
            next = types.KeyboardButton('Начать вопросы к тексту 2')
            markup.row(next)
            exit_from_vocabulary = types.KeyboardButton('Меню')
            markup.row(exit_from_vocabulary)
            bot.send_message(message.chat.id, 'Готов ли ты к вопросу?', reply_markup=markup)
            bot.register_next_step_handler(message, on_click)
        if results[0][0]==2:
            markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
            menu = types.KeyboardButton("Меню")
            markup.row(menu)
            bot.send_message(message.chat.id, 'К сожалению, ты прошел все задания. Возвращайся позже', reply_markup=markup)
            bot.register_next_step_handler(message, on_click)

    if message.text == 'Начать вопросы к тексту 1':
        bot.send_message(message.chat.id, 'Вопрос 1.1. Mark’s business in Bristol was successful.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('1.1.True')
        btn_2 = types.KeyboardButton('1.1.False')
        btn_3 = types.KeyboardButton('1.1.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '1.1.':
        bot.send_message(message.chat.id, 'Ответ на вопрос 1.1: True')
        bot.send_message(message.chat.id, 'Вопрос 1.2. Mark bought an expensive caravan for his new life.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('1.2.True')
        btn_2 = types.KeyboardButton('1.2.False')
        btn_3 = types.KeyboardButton('1.2.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '1.2.':
        bot.send_message(message.chat.id, 'Ответ на вопрос 1.2: False')
        bot.send_message(message.chat.id, 'Вопрос 1.3. Mark’s family approved of his moneyless project.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('1.3.True')
        btn_2 = types.KeyboardButton('1.3.False')
        btn_3 = types.KeyboardButton('1.3.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '1.3.':
        bot.send_message(message.chat.id, 'Ответ на вопрос 1.3: Not stated')
        bot.send_message(message.chat.id, 'Вопрос 1.4. The only thing Mark couldn’t give up was coffee.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('1.4.True')
        btn_2 = types.KeyboardButton('1.4.False')
        btn_3 = types.KeyboardButton('1.4.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '1.4.':
        bot.send_message(message.chat.id, 'Ответ на вопрос 1.4: False')
        bot.send_message(message.chat.id, 'Вопрос 1.5. Mark got food from different sources.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('1.5.True')
        btn_2 = types.KeyboardButton('1.5.False')
        btn_3 = types.KeyboardButton('1.5.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '1.5.':
        bot.send_message(message.chat.id, 'Ответ на вопрос 1.5: True')
        bot.send_message(message.chat.id, 'Вопрос 1.6. People’s attitudes towards Mark’s project were different.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('1.6.True')
        btn_2 = types.KeyboardButton('1.6.False')
        btn_3 = types.KeyboardButton('1.6.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '1.6.':
        bot.send_message(message.chat.id, 'Ответ на вопрос 1.6: True')
        bot.send_message(message.chat.id, 'Вопрос 1.7. Some of Mark’s fans want to repeat his experiment.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('1.7.True')
        btn_2 = types.KeyboardButton('1.7.False')
        btn_3 = types.KeyboardButton('1.7.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '1.7.':
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Ответ на вопрос 1.7: Not stated')
        connection = sqlite3.connect('users_data.sql')
        cursor = connection.cursor()
        cursor.execute('UPDATE Users SET learnt_texts = ? WHERE id = ?', (1, message.from_user.id))
        connection.commit()
        connection.close()
        bot.send_message(message.chat.id, 'Это был последний вопрос! Хорошая работа!', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)

    if message.text == 'Начать вопросы к тексту 2':
        bot.send_message(message.chat.id, 'Вопрос 2.1. Nike and Blue Ribbon Shoes are the names for one and the same business.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('2.1.True')
        btn_2 = types.KeyboardButton('2.1.False')
        btn_3 = types.KeyboardButton('2.1.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '2.1.':
        bot.send_message(message.chat.id, 'Ответ на вопрос 2.1: True')
        bot.send_message(message.chat.id, 'Вопрос 2.2. The business was founded by Japanese businessmen.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('2.2.True')
        btn_2 = types.KeyboardButton('2.2.False')
        btn_3 = types.KeyboardButton('2.2.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '2.2.':
        bot.send_message(message.chat.id, 'Ответ на вопрос 2.2: False')
        bot.send_message(message.chat.id, 'Вопрос 2.3. The business started with renting a large shop.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('2.3.True')
        btn_2 = types.KeyboardButton('2.3.False')
        btn_3 = types.KeyboardButton('2.3.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '2.3.':
        bot.send_message(message.chat.id, 'Ответ на вопрос 2.3: False')
        bot.send_message(message.chat.id, 'Вопрос 2.4. Famous athletes were employed to advertise the company’s shoes.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('2.4.True')
        btn_2 = types.KeyboardButton('2.4.False')
        btn_3 = types.KeyboardButton('2.4.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '2.4.':
        bot.send_message(message.chat.id, 'Ответ на вопрос 2.4: Not Stated')
        bot.send_message(message.chat.id, 'Вопрос 2.5. The company Nike was called after a character from an ancient myth.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('2.5.True')
        btn_2 = types.KeyboardButton('2.5.False')
        btn_3 = types.KeyboardButton('2.5.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '2.5.':
        bot.send_message(message.chat.id, 'Ответ на вопрос 2.5: True')
        bot.send_message(message.chat.id, 'Вопрос 2.6. Nike’s logo was created by a famous advertising company.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('2.6.True')
        btn_2 = types.KeyboardButton('2.6.False')
        btn_3 = types.KeyboardButton('2.6.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '2.6.':
        bot.send_message(message.chat.id, 'Ответ на вопрос 2.6: False')
        bot.send_message(message.chat.id, 'Вопрос 2.7. The Nike company paid a large amount of money for creating the slogan «Just Do It».')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('2.7.True')
        btn_2 = types.KeyboardButton('2.7.False')
        btn_3 = types.KeyboardButton('2.7.Not stated')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:4] == '2.7.':
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Ответ на вопрос 2.7: Not stated')
        connection = sqlite3.connect('users_data.sql')
        cursor = connection.cursor()
        cursor.execute('UPDATE Users SET learnt_texts = ? WHERE id = ?', (2, message.from_user.id))
        connection.commit()
        connection.close()
        bot.send_message(message.chat.id, 'Это был последний вопрос! Хорошая работа!', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)

    if message.text == 'Грамматика':
        connection = sqlite3.connect('users_data.sql')
        cursor = connection.cursor()
        cursor.execute('SELECT learnt_grammar FROM Users WHERE id == ?', (message.from_user.id,))
        results = cursor.fetchall()
        cursor.close()
        connection.close()
        if results[0][0]==0:
            markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
            next = types.KeyboardButton('Начать вопросы по грамматике 1')
            markup.row(next)
            exit_from_vocabulary = types.KeyboardButton('Меню')
            markup.row(exit_from_vocabulary)
            bot.send_message(message.chat.id, 'Готов ли ты к вопросу по грамматике?', reply_markup=markup)
            bot.register_next_step_handler(message, on_click)
        if results[0][0]==1:
            markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
            next = types.KeyboardButton('Начать вопросы по грамматике 2')
            markup.row(next)
            exit_from_vocabulary = types.KeyboardButton('Меню')
            markup.row(exit_from_vocabulary)
            bot.send_message(message.chat.id, 'Готов ли ты к вопросу по грамматике?', reply_markup=markup)
            bot.register_next_step_handler(message, on_click)
        if results[0][0]==2:
            markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
            menu = types.KeyboardButton("Меню")
            markup.row(menu)
            bot.send_message(message.chat.id, 'К сожалению, ты прошел все задания. Возвращайся позже', reply_markup=markup)
            bot.register_next_step_handler(message, on_click)

    if message.text == 'Начать вопросы по грамматике 1':
        bot.send_message(message.chat.id, 'Вопрос 1_1. What is this? … is my exercise-book.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('1_1. it')
        btn_2 = types.KeyboardButton('1_1. these')
        btn_3 = types.KeyboardButton('1_1. those')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:3] == '1_1':
        bot.send_message(message.chat.id, 'Ответ на вопрос 1_1 it')
        bot.send_message(message.chat.id, 'Вопрос 1_2. There is … pen on the table.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('1_2.some')
        btn_2 = types.KeyboardButton('1_2.such')
        btn_3 = types.KeyboardButton('1_2.a')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:3] == '1_2':
        bot.send_message(message.chat.id, 'Ответ на вопрос 1_2 a')
        bot.send_message(message.chat.id, 'Вопрос 1_3. … car is this?')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('1_3.what')
        btn_2 = types.KeyboardButton('1_3.whose')
        btn_3 = types.KeyboardButton('1_3.who’s')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:3] == '1_3':
        bot.send_message(message.chat.id, 'Ответ на вопрос 1_3 whose')
        bot.send_message(message.chat.id, "Вопрос 1_4. I’m cold. …open the window.")
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('1_4. a not')
        btn_2 = types.KeyboardButton("1_4. don’t")
        btn_3 = types.KeyboardButton('1_4. none')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:3] == '1_4':
        bot.send_message(message.chat.id, "Ответ на вопрос 1_4: don't")
        bot.send_message(message.chat.id, 'Вопрос 1_5. He … to the University by tram.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('1_5. is going')
        btn_2 = types.KeyboardButton('1_5. can')
        btn_3 = types.KeyboardButton('1_5. goes')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:3] == '1_5':
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Ответ на вопрос 1_5: goes')
        connection = sqlite3.connect('users_data.sql')
        cursor = connection.cursor()
        cursor.execute('UPDATE Users SET learnt_grammar = ? WHERE id = ?', (1, message.from_user.id))
        connection.commit()
        connection.close()
        bot.send_message(message.chat.id, 'Это был последний вопрос! Хорошая работа!', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)

    if message.text == 'Начать вопросы по грамматике 2':
        bot.send_message(message.chat.id, 'Вопрос 2.1. Nick … a book now.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('2_1. is reading')
        btn_2 = types.KeyboardButton('2_1.are reading')
        btn_3 = types.KeyboardButton('2_1.read will read')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:3] == '2_1':
        bot.send_message(message.chat.id, 'Ответ на вопрос 2_2 is reading')
        bot.send_message(message.chat.id, 'Вопрос 2_2. I like potatoes, but I … them everyday.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton("2_2.don’t eat")
        btn_2 = types.KeyboardButton("2_2.haven’t eat")
        btn_3 = types.KeyboardButton('2_2.not eat')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:3] == '2_2':
        bot.send_message(message.chat.id, 'Ответ на вопрос 2_2 don’t eat')
        bot.send_message(message.chat.id, 'Вопрос 2_3.  I … to see my friend tomorrow.')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('2_3.are going')
        btn_2 = types.KeyboardButton('2_3.have going')
        btn_3 = types.KeyboardButton('2_3. am going')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:3] == '2_3':
        bot.send_message(message.chat.id, 'Ответ на вопрос 2_3 am going')
        bot.send_message(message.chat.id, "Вопрос 2_4. She didn’t … breakfast yesterday.")
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('2_4. had')
        btn_2 = types.KeyboardButton("2_4. has")
        btn_3 = types.KeyboardButton('2_4. have')
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:3] == '2_4':
        bot.send_message(message.chat.id, "Ответ на вопрос 2_4: have")
        bot.send_message(message.chat.id, 'Вопрос 2_5. I can swim, but my friend …')
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('2_5. is not')
        btn_2 = types.KeyboardButton("2_5. can't")
        btn_3 = types.KeyboardButton("2_5. haven't")
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, 'Верно ли?', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text[0:3] == '2_5':
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, "Ответ на вопрос 2_5: can't")
        connection = sqlite3.connect('users_data.sql')
        cursor = connection.cursor()
        cursor.execute('UPDATE Users SET learnt_grammar = ? WHERE id = ?', (2, message.from_user.id))
        connection.commit()
        connection.close()
        bot.send_message(message.chat.id, 'Это был последний вопрос! Хорошая работа!', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)

    if message.text == 'Переводчик':
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton('С английского на русский')
        btn_2 = types.KeyboardButton("С русского на английский")
        btn_3 = types.KeyboardButton("Меню")
        markup.row(btn_1, btn_2)
        markup.row(btn_3)
        bot.send_message(message.chat.id, 'Выбери языки', reply_markup=markup)
        bot.register_next_step_handler(message, on_click)
    if message.text == 'С английского на русский':
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        btn_1 = types.KeyboardButton("Меню")
        markup.row(btn_1)
        bot.send_message(message.chat.id, "Введите слово", reply_markup=types.ReplyKeyboardRemove(), parse_mode='Markdown')
        types.ReplyKeyboardRemove()
        @bot.message_handler(content_types=['text'])
        def tranclate(message):
            bot.send_message(message.chat.id, translate(message.text, 'английский'), reply_markup=markup)
            bot.register_next_step_handler(message, on_click)
    elif message.text == 'С русского на английский':
        markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
        menu = types.KeyboardButton("Меню")
        markup.row(menu)
        bot.send_message(message.chat.id, "Введите слово", reply_markup=types.ReplyKeyboardRemove(), parse_mode='Markdown')
        bot.send_message(message.chat.id, 'Введите слово')
        @bot.message_handler(content_types=['text'])
        def tranclate(message):
            bot.send_message(message.chat.id, translate(message.text, 'русский'), reply_markup=markup)
            bot.register_next_step_handler(message, on_click)

bot.polling(none_stop=True)
